# Generated by Django 5.1.4 on 2025-01-05 21:18

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='QuizUser',
            new_name='QuizzerUser',
        ),
        migrations.RenameModel(
            old_name='Quiz',
            new_name='Quizzes',
        ),
    ]
