# Generated by Django 5.1.5 on 2025-01-27 10:15

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_rename_quizuser_quizzeruser_rename_quiz_quizzes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizzes',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
    ]
